Bugfix/linux task tracking
S2E/s2e-linux-kernel pull request #4
Opened 2017-07-25 17:59 UTC by adrianherrera

Refactoring to get `LinuxMonitor::getPid` to function correctly (see https://github.com/S2E/libs2eplugins/pull/12).

The LinuxMonitor plugin currently uses the approach described at https://stackoverflow.com/questions/11961490/understanding-the-getting-of-task-struct-pointer-from-process-kernel-stack to get the current task_struct and hence the PID of the process currently running in the system. Unfortunately, this approach is only valid for kernel versions < 4.x In kernel versions > 4.x the only way to get the current task_struct is via the get_current function (arch/$(ARCH)/include/asm/current.h). This required some major refactoring to get this information to the LinuxMonitor plugin. 

We introduced a new dynamic module, linuxmonitor. When loaded this module sends crucial information on kernel addresses and data structures to the LinuxMonitor plugin, including the address of the current task_struct pointer. With this information, the LinuxMonitor plugin is able to correctly track the current PID in the kernel.  We can also send offset values to the LinuxMonitor plugin, which makes the plugin architecture independent and more easily ported to kernels (previously these offsets were hardcoded into the LinuxMonitor plugin itself). 

This module has the added bonus that we can correctly check if the LinuxMonitor plugin is enabled when we resume from a snapshot. Previously, the LinuxMonitor plugin was checked only at kernel boot. However, when resuming from a snapshot the LinuxMonitor plugin may be in a different state (i.e. enabled or disabled) than that when the booted was originally booted. 

Finally, we rearchitectured the S2E modifications so that they can be completely disabled via a Kconfig option.

This goes with https://github.com/S2E/guest-tools/pull/6

2017-07-30 10:28 UTC, vitalych commented on linux-4.9.3/config-x86_64
> +CONFIG_S2E=y
Very nice idea

2017-07-30 10:29 UTC, vitalych commented on linux-4.9.3/kernel/s2e/s2e.c
> +static int __init s2e_init(void) {
Does this conform to Linux code style? (tabs for indent, space for alignment)

2017-07-30 10:30 UTC, vitalych commented on linux-4.9.3/kernel/s2e/s2e.c
> +MODULE_LICENSE("GPL");
MIT

2017-07-30 10:32 UTC, vitalych requested changes
minor comments

2017-07-30 10:52 UTC, vitalych commented
Is s2e module built by default?

2017-07-30 19:37 UTC, adrianherrera commented on linux-4.9.3/kernel/s2e/s2e.c
> +static int __init s2e_init(void) {
Hmm actually no. I'll fix this.

2017-07-30 19:38 UTC, adrianherrera commented
Yes, the module is built by default if `CONFIG_S2E` is enabled.

2017-07-30 19:49 UTC, adrianherrera commented
Fixed s2e.c formatting. Ready to be reviewed again.

2017-07-31 13:56 UTC, adrianherrera commented
I've also ported the kernel module to the Decree kernel.

2017-08-06 12:03 UTC, vitalych approved these changes

2017-08-06 17:15 UTC, merged